name: mystery_model_visualize
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: tejag <tejainece@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  c3:
  grizzly_io: ^2.0.1

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
